{
    'name': 'MEMs Master',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://www.appcode.co.th/mems',
    'category': 'Custom',
    'depends': ['base', 'mems_theme'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/paper_format.xml',
        'report/spare_part_qrcode.xml',
        'report/spare_part_form.xml',
        'data/brand_data.xml',
        'data/department_data.xml',
        'data/stock_location_data.xml',
        'data/supplier_data.xml',
        'data/payment_term_data.xml',
        'data/bank_data.xml',
        'data/category_data.xml',
        'data/uom_category_data.xml',
        'data/uom_data.xml',
        'data/spare_part_data.xml',
        'data/reason_data.xml',
        'views/menu.xml',
        'views/brand_view.xml',
        'views/department_view.xml',
        'views/stock_location_view.xml',
        'views/supplier_view.xml',
        'views/payment_term_view.xml',
        'views/bank_account_view.xml',
        'views/spare_part_view.xml',
        'views/reason_view.xml',
        'views/category_view.xml',
        'views/uom_view.xml',
        'views/uom_category_view.xml',
        'views/company_view.xml',
        'wizard/spare_part_adjust_wizard.xml',
    ],
    'demo': [],
}
