{
    'name': 'MEMs Purchase',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://www.appcode.co.th/mems',
    'category': 'Custom',
    'depends': ['base', 'mail', 'mems_master'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'report/paper_format.xml',
        'report/rfq_form.xml',
        'report/purchase_form.xml',
        'data/sequence.xml',
        'data/email_data.xml',
        'views/menu.xml',
        'views/rfq_view.xml',
        'views/purchase_view.xml',
        'views/payment_view.xml',
        'wizard/rfq_cancel_wizard.xml',
        'wizard/rfq_approve_wizard.xml',
        'wizard/po_cancel_wizard.xml',
        'wizard/po_approve_wizard.xml',
        'wizard/payment_wizard.xml',
    ],
    'demo': [],
}
